telegrambot:
    image: pablokbs/pelade-transmission-bot
    restart: unless-stopped
    command: python /code/transmission_bot/telegram_bot.py
    environment:
      - ADDRESS=transmission
      - PORT=9091
      - TS_USER=usuario
      - PASSWORD=contraseÑa
      - TOKEN=TOKEN
      - PERSISTENCE_FILE=/var/lib/transmission-telegram/authorized_chats
